README.md
As far as I can tell, you need to change
```vim
let g:syntastic_javascript_checkers = ['eslint']
```
to
```vim
let g:syntastic_javascript_checkers = ['eslint_d']
```
in your `.vimrc`.
=> Document vim syntastic javascript checkers

bin/eslint_d.js, lib/client.js, lib/linter.js, lib/options.js, lib/server.js, package.json
Allows IDEs to pass in code via stdin. Fixes #13.
=> Porting eslint's stdin logic to eslint_d

README.md, bin/eslint.js
By adding a symlink, we can take advantage of the eslint_d inside of the WebStorm IDE
This does not add eslint to the npm bin, but just make sure `eslint.js` exists for tools and plugins that look for it.
Add eslint_d to WebStorm's ESLint config
Without this patch, we get the following error.
With the patch, the linter is faster than ever!
=> Add eslint.js for WebStorm compat

.eslintrc, package.json
Hello.
Since eslint 2.0 was released the `keyword-spacing`  rule is now the standard.
Running the test with eslint installed globally will fail because of this rule.
Is this something you guys would be interested in updating, since it creates a dependency
on 2.0 and probably needs a major release of eslint_d ?
I can help with that if needed.
I just came across this issue because of using eslint_d as a sublime linter plugin on a new project and it failing.
=> update eslint to 2.2.0

lib/linter.js
in the use case when eslint is installed locally with 3rd party
configurations, for example: eslint-config-airbnb. However chalk is not
installed locally, this will cause an exception and goes into the catch
clause and load eslint and chak from eslint_d.
Now eslint will not able to find eslint-config-airbnb which installed
locally.
I split the try-catch clause, so that eslint and chalk will be loaded
separately. Means eslint will be resolved from local, and whether there
is eslint at local, it does not effect the way how chalk will be loaded.
=> requre chalk in another try-catch

lib/options.js, package.json
A [recent change](https://github.com/eslint/eslint/commit/bda5de56d13e5aea3857dd9c78d2edde59d3dffa) removed `espree` as the explicit default parser in `eslint` as it was causing issues with users using `babel-eslint` as their parser. Possibly related to https://github.com/mantoni/eslint_d.js/issues/21 and https://github.com/mantoni/eslint_d.js/issues/40.
=> Remove espree as the default parser

README.md, lib/client.js, lib/launcher.js, lib/portfile.js, lib/server.js
This PR introduces a security token that is generated on server startup and is stored along with the port number in `~/.eslint_d`. Each request has to prepend the token, separated by a blank from the remaining payload. Requests without a matching token will be ignored.
While this is a security fix, I am tempted to release this as a patch. However, at the same time this introduces a protocol break which will cause issues with [eslintme](https://github.com/ruyadorno/eslintme). Fortunately, eslintme did not upgrade to `3.x` or `4.x` yet, so it should not cause any damage. I don't know of anybody else using the wire protocol.
Please send your feedback on this @moll and @ruyadorno. Thanks.
=> Introduce security token and bind to 127.0.0.1

README.md, lib/linter.js, lib/options.js
=> Add --fix-to-stdout

lib/linter.js
Previously it printed the help message instead of nothing.
We may not even need the check because this function is typically called by eslint_d.js itself, but it doesn't hurt.
=> Fix --fix-to-stdout with empty file

lib/server.js
This is a less graceful approach to stopping the server, but it allows for
editors to hold a connection open to make for an even faster response time.
I have a version of eslintd-fix in the works that uses this technique and
achieves fixes that are pretty close to as fast as atom/vscode are capable of
with their in process eslint.
=> Force all open connections to close when the server is stopped

lib/launcher.js
Rationale
Passthrough environment variables to the spawn process. This is the default behavior of `child_process.spawn` when `options` is undefined, see https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options.
The use case is we use environment variables to enforce a stricter eslint configuration on lint-staged.
```js
module.exports = {
extends: process.env.ESLINT_ENV="production" ? "../.eslintrc.strict" : "./.eslintrc"
}
```
=> fix(launcher): passthrough environment variables

lib/client.js, lib/launcher.js
If `localhost` doesn't resolve to `127.0.0.1`, the client cannot connect
to the server. This issue arose in https://github.com/josephfrazier/prettier_d/pull/7,
and I ported the changes from there.
=> Connect to 127.0.0.1 instead of localhost

bin/eslint_d.js, lib/launcher.js
This fixes #88 by restoring color support. The CLI explicitly adds `--no-color` to the arguments passed to eslint if colors are not supported which leads me to belive that color support used to work. Therefore the simple trick to add `FORCE_COLOR=1` to the environment when launching background processes does the trick.
This can be verified by running `eslint_d file.js` to see colors and `eslint_d file.js | less` to see no colors.
=> Fix color support

lib/connect.js, lib/launcher.js, test/launcher-test.js
In case the `eslint_d` client cannot connect, unlink the port file and relaunch a new instance transparently. This also adds a safety check to make sure a single client never launches more than one instance.
Inspired by #95, this is a solution for #61.
=> Handle obsolete portfile

.gitignore, .travis.yml, lib/linter.js, package.json, test/fixture/v4.0.x/package-lock.json, test/fixture/v4.0.x/package.json, test/fixture/v5.0.x/package-lock.json, test/fixture/v5.0.x/package.json, test/linter-test.js
This was an experiment done as part of the analysis for #99 to see if the current `eslint_d` implementation could run older `eslint` versions, like `v4.0` and `v5.0`.
It turns out there is only a minor change required to make this work: `eslint@4` requires `cwd` to be passed in as an aboslute path.
With this change, `npm` is instructed to install `eslint@4.0.x` and `eslint@5.0.x` in test fixture directories and the linter tests are executed against these version as well.
Note: Review with whitespace turned off since most of the test changes are indentation.
=> Run tests against eslint v4.0 and v5.0

lib/linter.js, lib/resolver.js, package-lock.json, package.json, test/linter-test.js
The cause of this issue is that `browserify/resolve` doesn't fully comply with Node's module resolution algorithm. 
Changing `browserify/resolve` with Node's `require.resolve` function solves this issue but breaks tests because Sinon is not able to spy on `require.resolve`. In fact each module has its own `require.resolve` instance, therefore I see 3 options how to fix tests (I implemented the **1st one**):
1. Wrap `require.resolve` in a function in a separate module and import it. Spy with Sinon on this wrapper function in the same way as on `browserify/resolve`. Not very nice but easy and works well.
2. Export `linter`'s `require.resolve` and spy on it. Works only while `require.resolve` is not used during `linter` module loading. This is the case for the moment, so it will work, but …
=> Fix issue #101: Error: Cannot find module 'chalk' from '$PROJECT_DIR/node_modules/eslint/lib'

lib/linter.js, test/linter-test.js
chalk no longer uses `enabled` property since [v3.0.0](https://github.com/chalk/chalk/releases/tag/v3.0.0).
Therefore `--no-color` option is not working.
This suggestion lets eslint_d use `level` property instead, so the problem would be fixed.
Thank you.
=> Use level property instead of enabled for chalk

lib/linter.js, test/linter-test.js
fixes #152 . `eslint_d --print-config` was failing with eslint 7.0.0+ but working for eslint <= 6.0.0 .
=> fix --print-config for eslint 7+ ; add test

lib/linter.js, test/linter-test.js
First pass at resolving #155, but I've kept it minimal so I can clarify a point before making further changes. 
This implementation only handles errors thrown by `executeWithESLint` and `executeWithCLIEngine`, which solves my specific case (handling broken / invalid configuration files) but leaves a bunch of other errors that [will cause ESLint to exit with code 2](https://github.com/eslint/eslint/commit/e4c3b3c5616319b7105c840de6e724f73f558ae0). 
`executeWithESLint` and `executeWithCLIEngine` each have a few places where they call `callback` directly with an error message string as the first argument. Would it be viable to replace those callback invocations with thrown errors instead, or is there something I'm missing? 
Also, wrapping the body of `invoke` in a try / catch block would …
=> Implement exit codes

lib/eslint-path.js, lib/linter.js, lib/options-cliengine.js, lib/options-eslint.js, test/eslint-path-test.js, test/linter-test.js
Allow passing an alternative path to an eslint module using the `--eslint-path` option. This will make it easier to support different module resolution schemes, such as Yarn PnP.
I went ahead and added this to the parsed options, so that it will also be shown if a user makes a call to `eslint_d --help`. Since this option determines which version of eslint will be used, we don't really know whether or not to parse options for the legacy `CLIEngine` or the `ESLint` class. Since we're only looking for the presence of `--eslint-path`, this really shouldn't matter, but it does mean we end up parsing options twice.
Closes #174
=> Support Passing Alternative Eslint Module Path

lib/linter.js, test/linter-test.js
Fixes #177 by supporting the following patterns when parsing `--eslint-path`:
1. `--eslint-path [path]`
1. `--eslint-path '[path]'`
1. `--eslint-path "[path]"`
1. `--eslint-path=[path]`
1. `--eslint-path='[path]'`
1. `--eslint-path="[path]"`
An ideal solution would be to use a more forgiving options parser than `optionator`, then pass the parsed options through a validator as a second step, but I didn't want to introduce that big of a change.
=> Support quotes when parsing --eslint-path

lib/linter.js, package-lock.json, package.json, test/linter-test.js
Fixes https://github.com/mantoni/eslint_d.js/issues/186. Depends on https://github.com/mantoni/core_d.js/pull/20.
=> Invalidate cache based on content hash rather than modification time

README.md, package-lock.json, package.json, test/linter-test.js
While ESLint 8 was supported by eslint_d for quite some time, the "fallback" was still ESLint 7.
=> Upgrade default eslint to v8.12.0

README.md, lib/eslint-path.js, lib/linter.js, test/eslint-path-test.js, test/linter-test.js
This PR aims to provide a way to only resolve local `eslint` binaries and thus fixing https://github.com/mantoni/eslint_d.js/issues/180.
It simply checks for environment variables and returns early before resolving binary globally.
Suggestions for improvements on name is appreciated! 👍🏼
=> fix: resolve local only env

lib/caches.js, lib/files-hash.js, lib/linter.js, package-lock.json, package.json, test/caches-test.js, test/files-hash-test.js, test/linter-test.js
As discovered in #198, invalidating the `eslint_d` internal caches based on common package manager file content changes is broken. The feature has now been removed from `core_d` v5 (see mantoni/core_d.js#23).
This PR upgrades `core_d` to v5 and implements the file checks for common package manager file in `eslint_d` instead. It now actually checks the files in the `cwd` and further optimises performance by only checking files that existed when the cache was created.
=> Migrate to core_d v5 and implement common package manager file checks

README.md
SublimeLinter-eslint (SublimeLinter/SublimeLinter-eslint/releases/tag/4.3.0) supports 
`eslint_d` out of the box.
=> Update Sublime Text information in README

lib/linter.js, test/linter-test.js
At https://codesandbox.io/projects we are happily using this library, so thank you so much for the effort here 🙏 ❤️ 
What we have experienced though is that the process exits with an unhandled promise exception when it receives a message and no ESLint can be resolved. Looking at the code it makes perfect sense that this happens because indeed `getCache` will throw an error when no ESLint is found.
I assume this is not intended behaviour as this process just takes any path which might have ESLint available or not, the TCP server should never exit unless asked to do so.
I would also assume this is not discovered because most people using this library defaults to using the internal ESLint when none available. For us though it is crucial to only use ESLint if it is actually available.
We are …
=> Prevent unhandled promise exception

lib/caches.js
I noticed that on Windows when trying to run `eslint_d` I was getting a type error saying something along th elines of eslint not being defined. I managed to track it down to the fact that in the PR [`absolute_eslint_path.replace()` was used](https://github.com/mantoni/eslint_d.js/pull/277/files#diff-6392a3a5106e8337ca42d13255dea882977d0c0a0f924663e17bb65acc84dc68R48-R51) to update the path for eslint.
This seems to not work on windows as the paths there use double backslash like `node_modules\\.pnpm\\eslint@8.54.0\\node_modules\\eslint\\lib\\api.js`.
In this PR I replaced it with `path.join` and `path.dirname`. Let me know if you have any questions or if there is something else that works too and you'd prefer me to use.
=> feat: support eslint flat config on windows

lib/linter.js
- Filters 'reportUnusedDisableDirectives' removed in https://github.com/eslint/eslint/commit/0dd9704c4751e1cd02039f7d6485fee09bbccbf6
Fixes #283.
=> fix: adds ability to filter cli options before passing to eslint

bin/eslint_d.js, lib/hash.js, lib/hash.test.js
The filenames where resolved relative to `process.cwd()` which means they're missing when calling `eslint_d` from a sub-directory. This would unnecessarily restart the server.
Fixes #296
=> Fix hash when changing directories

lib/forwarder.js, lib/forwarder.test.js, lib/service.js, lib/service.test.js
The previous implementation only worked for exit codes of one character and had repeated magic numbers.
This is mainly the work of @DamienCassou from #301. I changed the exit code token to have fixed length of 7 characters, padding the exit code with zeros. This allowed to simplify the response handling logic a bit.
=> Refactor forwarder to remove a limitation in the size of the error code

lib/resolver.js, lib/resolver.test.js, package-lock.json
on Windows machines another path separator is used,
so instead of "/path/to/eslint/lib/eslint.js" we get
"C:\\path\\to\\eslint\\lib\\eslint.js".
Provided fix uses require.resolve of package.json which is
always at top-level and then passthrough it to dirname function,
which will return path to eslint package with correct path separators.
=> fix(resolver): eslint path detection not working on Windows

README.md, lib/config.js, lib/config.test.js, lib/forwarder.js, lib/forwarder.test.js, lib/help.js, test/test.integration.js
This includes the work from @DamienCassou made in #298 with  more unit tests and documentation.
Fixes #295
=> Add --fix-to-stdout back

lib/daemon.test.js, lib/forwarder.test.js, lib/hash.test.js, lib/resolver.test.js
most of failures were related to "/" vs "\" in paths,
I've wrapped them in `normalize` from `node:path` module
to replace path delimiter character with proper one for
current OS.
=> chore: fix unit tests on Windows

.github/workflows/ci.yml, lib/daemon.js, lib/launcher.js, lib/launcher.test.js, lib/service.js, lib/service.test.js, test/test.integration.js
=> fix: stop command not working on Windows OS

.gitignore, lib/launcher.test.js, package-lock.json, package.json
Allow to see a coverage report with `npm run test:coverage`.
- Prints summary on the command line
- Generates a browsable v8 coverage report (`open coverage-reports/index.html`)
=> Add test:coverage script

bin/eslint_d.js, lib/commands.js, lib/forwarder.js, lib/forwarder.test.js, lib/launcher.js, lib/launcher.test.js, lib/service.js, lib/service.test.js, lib/status.js, lib/status.test.js
Based on #316
In this PR:
- Implemented isAlive check for start and status commands
- Added separated option for commands in forwarder and service
- Created helper function to obtain socket in forwarder
=> feat: implement is alive check

lib/forwarder.js, lib/forwarder.test.js
Based on #317 
In scope of this PR:
- Launch daemon on **first** ECONNREFUSED while executing lint command
=> feat: launch daemon on forward failure

lib/forwarder.js
Replaced event listened in `connectToDaemon`
Fixes #319
=> fix: unhandled 'error' event

README.md, bin/eslint_d.js, lib/config.js, lib/daemon.js, lib/forwarder.js, lib/forwarder.test.js, lib/help.js, lib/launcher.js, lib/launcher.test.js, lib/service.js, lib/service.test.js, package-lock.json, package.json
This uses the `debug` module that ships with `eslint` to print debug output to a separate terminal.
Usage notes are in the second commit.
Fixes #322
=> Add support for `--debug`

.github/workflows/ci.yml, package-lock.json, package.json
On node `v23.1.0`, invocations of `eslint_d` print this warning:
```
(node:21499) ExperimentalWarning: CommonJS module .../node_modules/debug/src/node.js is loading ES
Module .../node_modules/supports-color/index.js using require().                                          
Support for loading ES Module in require() is an experimental feature and might change at any time
```
The cause of this is that `eslint_d` has a direct dependency to `supports-color@^9` which is ESM, while `eslint` depends on `supports-color@^7` through `chalk` which is CJS.
This change downgrades `supports-color` to `v7` to only have the CJS version installed. With this, the warning is not showing anymore.
=> Downgrade supports-color to same version as eslint

README.md, lib/help.js, lib/resolver.js, lib/resolver.test.js
Fixes #242 
When `ESLINT_ROOT` is provided, attempt to resolve eslint from that path before checking `process.cwd`
This seemed like the simplest approach to me without re-working all of `ESLINT_D_MISS` behavior
=> Allow overriding eslint path with environment var
